/* Generated by scripts/prepare-assets.mjs — do not edit by hand.
 * Source: public/references/before-after-legs.png (sha256:e48207e0a38bbab2)
 * Re-run the script only when that photograph is replaced. */

export interface SceneImage {
  id: string;
  width: number;
  height: number;
  /** Flat colour of the crop: fills the slot before the photo arrives. */
  placeholder: string;
  /** 20 px blur of the same crop, inlined (R04.1). */
  blurDataUri: string;
  sources: readonly { type: string; srcSet: string }[];
  src: string;
}

export const SCENE_WIDTHS = [250, 374, 498] as const;

/**
 * The left silhouette of the leg as measured on this crop: x = x0 + slope·y.
 * The scene puts the applicator and the hair strokes on the leg with it, so
 * replacing the photograph moves them with the leg instead of leaving them
 * behind.
 */
export const SHIN_EDGE = { x0: 297.533, slope: -0.58624 } as const;

export const LEG_BEFORE: SceneImage = {
  id: 'leg-before',
  width: 498,
  height: 720,
  placeholder: '#c18a6e',
  blurDataUri:
    'data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAQBQCdASoUAB0APtFcqU4oJSQiKAqpABoJYwC7M47BqgDg6GdShwNHue14zDJrfugAAP7THZxL9unmuVk3w52MiA/cJjB4NzJUWSXQ1rbzyxcHMMbAX4+F7bFAzuPgAAA=',
  sources: [
    { type: 'image/avif', srcSet: '/scenes/leg-before-250.avif 250w, /scenes/leg-before-374.avif 374w, /scenes/leg-before-498.avif 498w' },
    { type: 'image/webp', srcSet: '/scenes/leg-before-250.webp 250w, /scenes/leg-before-374.webp 374w, /scenes/leg-before-498.webp 498w' },
    { type: 'image/png', srcSet: '/scenes/leg-before-250.png 250w, /scenes/leg-before-374.png 374w, /scenes/leg-before-498.png 498w' },
  ],
  src: '/scenes/leg-before-498.png',
};

export const LEG_AFTER: SceneImage = {
  id: 'leg-after',
  width: 498,
  height: 720,
  placeholder: '#c78d70',
  blurDataUri:
    'data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQBACdASoUAB0APtFep04oJSOiKAqpABoJYwCuHBDRAyozr7spIGXUmkNp3tOiAAD+0yzzp4TbCxOc0tu4Ez9h5WjUGqPGf7/OI9WaeZ2G196xYH/CC7AA',
  sources: [
    { type: 'image/avif', srcSet: '/scenes/leg-after-250.avif 250w, /scenes/leg-after-374.avif 374w, /scenes/leg-after-498.avif 498w' },
    { type: 'image/webp', srcSet: '/scenes/leg-after-250.webp 250w, /scenes/leg-after-374.webp 374w, /scenes/leg-after-498.webp 498w' },
    { type: 'image/png', srcSet: '/scenes/leg-after-250.png 250w, /scenes/leg-after-374.png 374w, /scenes/leg-after-498.png 498w' },
  ],
  src: '/scenes/leg-after-498.png',
};

/** Both layers share one box, so the scene reserves it once (CLS = 0). */
export const SCENE_ASPECT_RATIO = 498 / 720;
